name: flutter_gank_io
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_redux: ^0.5.2
  event_bus: ^1.0.1
  shared_preferences: ^0.4.3
  dio: 1.0.9
  objectdb: ^1.0.5
  path_provider: ^0.5.0
  connectivity: ^0.3.2
  pull_to_refresh: ^1.1.6
  cached_network_image: ^0.7.0
  flutter_webview_plugin: ^0.3.0+2
  fluttertoast: ^2.2.2
  url_launcher: ^4.0.3
  photo_view: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - images/gank.png
      - images/favorite_empty.png
  fonts:
      - family: IconFont
        fonts:
          - asset: static/font/iconfont.ttf

      - family: WorkSansSemiBold
        fonts:
          - asset: static/font/WorkSans-SemiBold.ttf

      - family: WorkSansBold
        fonts:
          - asset: static/font/WorkSans-Bold.ttf

      - family: WorkSansMedium
        fonts:
          - asset: static/font/WorkSans-Medium.ttf

      - family: WorkSansLight
        fonts:
          - asset: static/font/WorkSans-Light.ttf
